name: Deploy

on:
  workflow_run:
    workflows: ["Build and Push"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    if: github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-slim
    env:
      DOTENV_PRIVATE_KEY: ${{ secrets.DOTENV_PRIVATE_KEY }}

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - run: curl -sfS https://dotenvx.sh/install.sh | sh

      - id: sa-key
        run: echo "json=$(dotenvx get BASE64_ENCODED_SERVICE_ACCOUNT_JSON)" >> $GITHUB_OUTPUT
      - uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          credentials_json: ${{ steps.sa-key.outputs.json }}

      - uses: google-github-actions/setup-gcloud@aa5489c8933f4cc7a4f7d45035b3b1440c9c10db # v3.0.1

      # shell format uses space not newline for some reason
      - run: dotenvx get --format shell -f terraform/.env | grep TF_VAR | sed 's/ /\n/g' >> $GITHUB_ENV

      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2

      - working-directory: terraform
        run: |
          terraform init
          terraform apply -auto-approve -input=false -replace=google_cloud_run_v2_service.n8n -replace=google_cloud_run_v2_service_iam_member.n8n_public_invoker
